package com.aug3.yhyc.dao;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

import org.apache.commons.lang.StringUtils;

import com.aug3.sys.util.DateUtil;
import com.aug3.sys.util.EncryptUtil;
import com.aug3.yhyc.base.CollectionConstants;
import com.aug3.yhyc.base.Constants;
import com.aug3.yhyc.dto.UserPrefs;
import com.aug3.yhyc.mail.MailSender;
import com.aug3.yhyc.util.ConfigManager;
import com.aug3.yhyc.util.IDGenerator;
import com.aug3.yhyc.util.Qiniu;
import com.aug3.yhyc.valueobj.User;
import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.WriteConcern;

public class UserDao extends BaseDao {

	private static final List<String> prefs_field = Arrays.asList(new String[] {
			"fav", "cart" });

	public User login(User user) {

		BasicDBObject dbObj = new BasicDBObject();

		if (user.getUid() != 0) {
			dbObj.append("_id", user.getUid());
		} else if (StringUtils.isNotBlank(user.getMobi())) {
			dbObj.append("mobi", user.getMobi());
		} else if (StringUtils.isNotBlank(user.getMail())) {
			dbObj.append("mail", user.getMail());
		}

		dbObj.append("password", user.getPassword());

		if (user.getType() == 99) {
			dbObj.append("type", user.getType());
		}

		DBObject userObj = getDBCollection(CollectionConstants.COLL_USERS)
				.findOne(dbObj);

		if (userObj != null) {

			BasicDBObject result = (BasicDBObject) userObj;

			return buildUser(result, false);

		} else {

			return null;
		}

	}

	public boolean isUserExist(User user) {

		BasicDBObject dbObj = new BasicDBObject();

		if (user.getUid() != 0) {
			dbObj.append("_id", user.getUid());
		} else if (StringUtils.isNotBlank(user.getMobi())) {
			dbObj.append("mobi", user.getMobi());
		} else if (StringUtils.isNotBlank(user.getMail())) {
			dbObj.append("mail", user.getMail());
		}

		long count = getDBCollection(CollectionConstants.COLL_USERS).count(
				dbObj);

		if (count == 0) {

			return false;

		} else {

			return true;
		}

	}

	/**
	 * use for get user avatar
	 * 
	 * @param uid
	 * @return
	 */
	public User find(long uid) {

		BasicDBObject dbObj = new BasicDBObject().append("_id", uid);

		DBObject userObj = getDBCollection(CollectionConstants.COLL_USERS)
				.findOne(dbObj);

		if (userObj != null) {

			BasicDBObject result = (BasicDBObject) userObj;

			return buildUser(result, true);
		}

		return null;

	}

	private User buildUser(BasicDBObject dbObj, boolean userPic) {

		User user = new User();
		user.setUid(dbObj.getLong("_id"));
		user.setName(dbObj.getString("name"));
		user.setMobi(dbObj.getString("mobi"));
		user.setMail(dbObj.getString("mail"));
		user.setAc(dbObj.containsField("ac") ? dbObj.getInt("ac") : 10);
		user.setShequ(dbObj.containsField("shequ") ? dbObj.getLong("shequ") : 0);
		user.setDist(dbObj.containsField("dist") ? dbObj.getInt("dist") : 0);

		String avatar = dbObj.getString("pic");

		if (StringUtils.isNotBlank(avatar)) {
			user.setHasAvatar(true);

			if (userPic)
				user.setAvatar(Qiniu.downloadUrl(avatar, Qiniu.getUserDomain()));
		}
		return user;
	}

	public static boolean isValidToken(String token) {

		if (EncryptUtil.MD5(DateUtil.formatCurrentDate()).equals(token))
			return true;
		else
			return false;
	}

	public long exist(User user) {

		BasicDBList or = new BasicDBList();
		or.add(new BasicDBObject().append("mobi", user.getMobi()));
		or.add(new BasicDBObject().append("mail", user.getMail()));

		DBObject result = getDBCollection(CollectionConstants.COLL_USERS)
				.findOne(new BasicDBObject("$or", or));

		if (result == null) {
			return 0;
		}

		BasicDBObject dbObj = (BasicDBObject) result;
		if (user.getMobi().equals(dbObj.getString("mobi"))) {
			return 1;
		} else if (user.getMail().equals(dbObj.getString("mail"))) {
			return 2;
		} else if (dbObj.getInt("sts") == 0) {
			return dbObj.getLong("_id");
		}

		return 3;

	}

	public long existByMobile(String mobile) {

		BasicDBObject query = new BasicDBObject("mobile", mobile);
		// sts == 0, this user may generated by system automatically when order
		// without register, can be merge next time he/she register

		DBObject result = getDBCollection(CollectionConstants.COLL_USERS)
				.findOne(query);

		if (result == null) {
			return 0;
		}

		return ((BasicDBObject) result).getLong("_id");
	}

	public long create(User user) {

		DBObject dbObj = new BasicDBObject();
		long uid = IDGenerator.nextUserID(getDB());
		dbObj.put("_id", uid);
		dbObj.put("name", user.getName());
		dbObj.put("password", user.getPassword());
		dbObj.put("mobi", user.getMobi());
		dbObj.put("mail", user.getMail());
		dbObj.put("job", user.getJob());
		dbObj.put("fav", new Long[] {});
		dbObj.put("cart", new Long[] {});
		dbObj.put("ac", 10);
		dbObj.put("sts", 1);
		dbObj.put("ts", new Date());

		getDBCollection(CollectionConstants.COLL_USERS).insert(dbObj);
		return uid;
	}

	public boolean modifyPassword(String mobi, String mail, String passwd) {

		int x = new Random().nextInt(7);
		x += 1;
		long t = System.currentTimeMillis() + 12 * 3600 * 1000 + x * 1016;

		getDBCollection(CollectionConstants.COLL_USERS).update(
				new BasicDBObject("mail", mail).append("mobi", mobi),
				new BasicDBObject("$set", new BasicDBObject("upwd", passwd)
						.append("upt", t)), false, false, WriteConcern.SAFE);

		MailSender.getInstance().sendPasswordNotification(mail, t);

		return true;
	}

	public boolean confirmPassword(String mail, long t) {

		DBObject dbObj = getDBCollection(CollectionConstants.COLL_USERS)
				.findOne(
						new BasicDBObject().append("mail", mail).append("upt",
								t));

		if (dbObj == null) {
			return false;
		}

		if (System.currentTimeMillis() > t) {
			return false;
		}

		String pwd = (String) dbObj.get("upwd");
		String pwd_origin = (String) dbObj.get("password");

		getDBCollection(CollectionConstants.COLL_USERS).update(
				new BasicDBObject("mail", mail),
				new BasicDBObject("$set", new BasicDBObject("password", pwd)
						.append("upwd", pwd_origin).append("upt",
								System.currentTimeMillis())), false, false,
				WriteConcern.SAFE);

		return true;
	}

	public void update(User user) {

		DBObject updateObj = new BasicDBObject();
		updateObj.put("name", user.getName());
		updateObj.put("password", user.getPassword());
		updateObj.put("mobi", user.getMobi());
		updateObj.put("mail", user.getMail());
		updateObj.put("sts", 1);
		updateObj.put("ts", new Date());

		getDBCollection(CollectionConstants.COLL_USERS).update(
				new BasicDBObject("_id", user.getUid()),
				new BasicDBObject("$set", updateObj), false, false,
				WriteConcern.SAFE);
	}

	public long createTemp(User user) {

		DBObject dbObj = new BasicDBObject();
		long uid = IDGenerator.nextUserID(getDB());
		dbObj.put("_id", uid);
		dbObj.put("name", user.getName());
		dbObj.put("mobi", user.getMobi());
		dbObj.put("ac", 10);
		dbObj.put("sts", 0);
		dbObj.put("ts", new Date());

		getDBCollection(CollectionConstants.COLL_USERS).insert(dbObj);
		return uid;
	}

	public List<Long> findFavorite(long uid) {

		DBCursor cur = getDBCollection(CollectionConstants.COLL_USERS).find(
				new BasicDBObject("_id", uid), new BasicDBObject("fav", 1));

		List<Long> items = new ArrayList<Long>();

		while (cur.hasNext()) {
			BasicDBObject dbo = (BasicDBObject) cur.next();
			BasicDBList favlist = (BasicDBList) dbo.get("fav");
			if (favlist != null && favlist.size() > 0) {

				for (Object itemid : favlist) {
					items.add((Long) itemid);
				}
			}
		}

		return items;
	}

	public UserPrefs findPrefs(long uid) {

		DBCursor cur = getDBCollection(CollectionConstants.COLL_USERS).find(
				new BasicDBObject("_id", uid),
				new BasicDBObject("fav", 1).append("cart", 1));

		UserPrefs userPrefs = new UserPrefs();

		while (cur.hasNext()) {
			BasicDBObject dbo = (BasicDBObject) cur.next();
			userPrefs.setFav((List<Long>) dbo.get("fav"));
			userPrefs.setCart((List<Long>) dbo.get("cart"));

		}

		String u = ConfigManager.getProperties().getProperty("urls");
		if (StringUtils.isNotBlank(u)) {
			String[] files = u.split(";");
			Map<String, String> urls = new HashMap<String, String>();
			for (String fn : files) {
				urls.put(
						fn,
						Qiniu.downloadUrl(fn + Constants.PNG,
								Qiniu.getCaipuDomain()));
			}
			userPrefs.setUrls(urls);
		}

		return userPrefs;
	}

	public void updatePoint(long uid, int district, long shequ) {

		BasicDBObject updateObj = new BasicDBObject();
		if (district > 0) {
			updateObj.append("dist", district);
		}
		if (shequ > 0) {
			updateObj.append("shequ", shequ);
		}

		getDBCollection(CollectionConstants.COLL_USERS).update(
				new BasicDBObject("_id", uid),
				new BasicDBObject("$set", updateObj));

	}

	public boolean addUserPrefs(long uid, String field, Collection<Long> items) {

		if (!prefs_field.contains(field) || items == null) {
			return false;
		}

		BasicDBObject updateObj = new BasicDBObject();

		updateObj.append("$addToSet", new BasicDBObject(field,
				new BasicDBObject("$each", items)));

		getDBCollection(CollectionConstants.COLL_USERS).update(
				new BasicDBObject("_id", uid), updateObj, false, false,
				WriteConcern.SAFE);

		return true;

	}

	public boolean removeUserPrefs(long uid, String field,
			Collection<Long> items) {

		if (!prefs_field.contains(field) || items == null) {
			return false;
		}

		BasicDBObject updateObj = new BasicDBObject().append("$pullAll",
				new BasicDBObject(field, items));

		getDBCollection(CollectionConstants.COLL_USERS).update(
				new BasicDBObject("_id", uid), updateObj, false, false,
				WriteConcern.SAFE);

		return true;

	}

	public boolean updateUserPrefs(long uid, String field,
			Collection<Long> items) {

		if (!prefs_field.contains(field) || items == null) {
			return false;
		}

		BasicDBObject updateObj = new BasicDBObject().append("$set",
				new BasicDBObject(field, items));

		getDBCollection(CollectionConstants.COLL_USERS).update(
				new BasicDBObject("_id", uid), updateObj, false, false,
				WriteConcern.SAFE);

		return true;

	}

	public List<Long> findFavWorks(long uid) {

		DBCursor cur = getDBCollection(CollectionConstants.COLL_USERS).find(
				new BasicDBObject("_id", uid), new BasicDBObject("works", 1));

		List<Long> items = new ArrayList<Long>();

		while (cur.hasNext()) {
			BasicDBObject dbo = (BasicDBObject) cur.next();
			List<Long> favlist = (List<Long>) dbo.get("works");
			if (favlist != null && favlist.size() > 0) {
				items.addAll(favlist);
			}
		}

		return items;
	}

	public List<Long> findShoppingCart(long uid) {

		DBCursor cur = getDBCollection(CollectionConstants.COLL_USERS).find(
				new BasicDBObject("_id", uid), new BasicDBObject("cart", 1));

		List<Long> items = new ArrayList<Long>();

		while (cur.hasNext()) {
			BasicDBObject dbo = (BasicDBObject) cur.next();
			BasicDBList cartList = (BasicDBList) dbo.get("cart");
			if (cartList != null && cartList.size() > 0) {

				for (Object itemid : cartList) {
					items.add((Long) itemid);
				}
			}
		}

		return items;
	}
}
